# Generated by Django 3.2.7 on 2022-03-16 22:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('video', models.FileField(null=True, upload_to='C:\\workspace\\sarvo-next\\activity_database\\2_code\\django\\src\\live_files\\media_root', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
            ],
        ),
        migrations.CreateModel(
            name='FreetimeActivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='free.medium')),
            ],
        ),
    ]
