# Generated by Django 3.2.7 on 2022-03-16 23:23

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0002_auto_20220316_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freetimeactivity',
            old_name='duration',
            new_name='activity_duration',
        ),
        migrations.AddField(
            model_name='freetimeactivity',
            name='activity_complexity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32), null=True, size=None),
        ),
        migrations.AddField(
            model_name='freetimeactivity',
            name='activity_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='freetimeactivity',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='freetimeactivity',
            name='original_url',
            field=models.URLField(default='Unkown Source', max_length=500),
        ),
        migrations.AddField(
            model_name='freetimeactivity',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32), null=True, size=None),
        ),
        migrations.AddField(
            model_name='freetimeactivity',
            name='valid_until',
            field=models.DateTimeField(null=True),
        ),
    ]
