# Generated by Django 3.2.7 on 2022-03-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0003_auto_20220317_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freetimeactivity',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
