# Generated by Django 3.2.7 on 2022-03-16 23:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0005_auto_20220317_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freetimeactivity',
            name='media',
        ),
        migrations.AddField(
            model_name='freetimeactivity',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='freetimeactivity',
            name='video',
            field=models.FileField(null=True, upload_to='C:\\workspace\\sarvo-next\\activity_database\\2_code\\django\\src\\live_files\\media_root', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.DeleteModel(
            name='Medium',
        ),
    ]
