# Generated by Django 3.2.7 on 2022-03-16 23:39

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0006_auto_20220317_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freetimeactivity',
            name='activity_complexity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='freetimeactivity',
            name='category_level_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='freetimeactivity',
            name='category_level_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='freetimeactivity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='freetimeactivity',
            name='original_url',
            field=models.URLField(blank=True, default='Unkown Source', max_length=500),
        ),
        migrations.AlterField(
            model_name='freetimeactivity',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='freetimeactivity',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='C:\\workspace\\sarvo-next\\activity_database\\2_code\\django\\src\\live_files\\media_root', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
