# Generated by Django 3.2.7 on 2022-03-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0007_auto_20220317_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freetimeactivity',
            name='activity_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freetimeactivity',
            name='activity_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
