# Generated by Django 3.2.7 on 2022-03-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0008_auto_20220317_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freetimeactivity',
            name='original_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
