# Generated by Django 3.2.6 on 2021-08-15 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='entryText',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='postTitle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='PostEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('imageSourceHref', models.CharField(default='', max_length=1000)),
                ('imageSourceText', models.CharField(default='', max_length=1000)),
                ('infoText', models.TextField(default='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
    ]
