# Generated by Django 3.2.6 on 2021-08-16 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210816_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postentry',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='posts.post'),
        ),
    ]
