# Generated by Django 3.2.7 on 2022-01-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_postentry_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(default='', max_length=1000)),
                ('value', models.FloatField(default=0)),
            ],
        ),
    ]
