from engine.transmission.push_notification_singleton import PNSingleton

class Device(object):

    def __init__(self):
        self.token = ""


if __name__ == "__main__":
    # Import Python code generated by Google's protobuf compiler:

    push = PNSingleton().chatPush("TEST", "BRUMBRUM")
    push.additional["event_id"] = 3
    push.post_ios(Device())
