# Generated by Django 3.2.7 on 2022-01-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_moneyentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyentry',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
