# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-12 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicFeedbackFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DateOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, default='Empty', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default='Empty', max_length=1000)),
                ('platform', models.CharField(blank=True, default='Empty', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5000)),
                ('sentTime', models.DateTimeField(default='2000-12-23T00:00:00Z')),
            ],
        ),
        migrations.CreateModel(
            name='SarvoEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Empty', max_length=100)),
                ('location', models.CharField(blank=True, default='Empty', max_length=150)),
                ('imageBase64', models.CharField(blank=True, default='Empty', max_length=1000000)),
                ('fixed_date', models.DateTimeField(default='2000-12-23T00:00:00Z')),
                ('description', models.CharField(blank=True, default='Empty', max_length=5000)),
                ('organization_status', models.CharField(blank=True, default='Empty', max_length=50)),
                ('fixed_date_option_id', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='SarvoEventChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rest.SarvoEvent')),
            ],
        ),
        migrations.CreateModel(
            name='SarvoGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Empty', max_length=100)),
                ('imageBase64', models.CharField(blank=True, default='Empty', max_length=1000000)),
                ('imagePreviewBase64', models.CharField(blank=True, default='Empty', max_length=1000000)),
                ('description', models.CharField(default='Empty', max_length=5000)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SarvoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Empty', max_length=100)),
                ('phonenumber', models.CharField(blank=True, default='Empty', max_length=50)),
                ('profilePictureBase64', models.CharField(blank=True, default='Empty', max_length=10000000)),
                ('profilePicturePreviewBase64', models.CharField(blank=True, default='Empty', max_length=1000000)),
                ('createdProfileDate', models.DateTimeField(default='2000-12-23T00:00:00Z')),
                ('role', models.CharField(blank=True, default='user', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SessionCacheModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('session_id', models.CharField(blank=True, default='Empty', max_length=100)),
                ('created', models.DateTimeField()),
                ('json_content', models.CharField(max_length=10000000)),
                ('url', models.CharField(max_length=200)),
                ('status_code', models.IntegerField(default=200)),
                ('body_hash', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserClickStreamModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('session_id', models.CharField(max_length=100)),
                ('device_id', models.CharField(blank=True, default='Empty', max_length=100)),
                ('interface_element_id', models.CharField(blank=True, default='Empty', max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('pixel_location_x', models.IntegerField()),
                ('pixel_location_y', models.IntegerField()),
                ('click_type', models.CharField(max_length=100)),
                ('next_page', models.CharField(default='Unknown', max_length=100)),
                ('current_page', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='sarvogroup',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admins', to='rest.SarvoUser'),
        ),
        migrations.AddField(
            model_name='sarvogroup',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='events', to='rest.SarvoEvent'),
        ),
        migrations.AddField(
            model_name='sarvogroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to='rest.SarvoUser'),
        ),
        migrations.AddField(
            model_name='sarvoevent',
            name='organizer',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='rest.SarvoUser'),
        ),
        migrations.AddField(
            model_name='sarvoevent',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to='rest.SarvoUser'),
        ),
        migrations.AddField(
            model_name='eventchatmessage',
            name='eventChat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.SarvoEventChat'),
        ),
        migrations.AddField(
            model_name='eventchatmessage',
            name='readBy',
            field=models.ManyToManyField(blank=True, related_name='read_by', to='rest.SarvoUser'),
        ),
        migrations.AddField(
            model_name='eventchatmessage',
            name='receivedBy',
            field=models.ManyToManyField(blank=True, related_name='received_by', to='rest.SarvoUser'),
        ),
        migrations.AddField(
            model_name='eventchatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.SarvoUser'),
        ),
        migrations.AddField(
            model_name='device',
            name='sarvoUser',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='rest.SarvoUser'),
        ),
        migrations.AddField(
            model_name='dateoption',
            name='acc_participants',
            field=models.ManyToManyField(related_name='acc_participants', to='rest.SarvoUser'),
        ),
        migrations.AddField(
            model_name='dateoption',
            name='dec_participants',
            field=models.ManyToManyField(related_name='dec_participants', to='rest.SarvoUser'),
        ),
        migrations.AddField(
            model_name='dateoption',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.SarvoEvent'),
        ),
        migrations.AddField(
            model_name='dateoption',
            name='inter_participants',
            field=models.ManyToManyField(related_name='inter_participants', to='rest.SarvoUser'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='contacts',
            field=models.ManyToManyField(related_name='contactsSarvo', to='rest.SarvoUser'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='sarvoUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rest.SarvoUser'),
        ),
    ]
