# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-14 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_sarvoevent_imagepreviewbase64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sarvouser',
            name='profilePicturePreviewBase64',
            field=models.CharField(blank=True, default='Empty', max_length=10000),
        ),
    ]
