# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-14 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20190614_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarvouser',
            name='isRegistered',
            field=models.BooleanField(default=True),
        ),
    ]
