# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-01 13:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest', '0004_sarvouser_isregistered'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarvouser',
            name='authenticationUser',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
