# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-09 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_sarvouser_authenticationuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sarvouser',
            name='phonenumber',
            field=models.CharField(blank=True, default='Empty', max_length=150),
        ),
    ]
