# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-18 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_auto_20191109_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sarvogroup',
            name='imageBase64',
            field=models.CharField(blank=True, default='Empty', max_length=10000000),
        ),
    ]
