# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-18 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_auto_20191118_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sarvoevent',
            name='imagePreviewBase64',
            field=models.CharField(blank=True, default='Empty', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='sarvouser',
            name='profilePicturePreviewBase64',
            field=models.CharField(blank=True, default='Empty', max_length=1000000),
        ),
    ]
