# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-12-19 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0010_auto_20191120_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarvouser',
            name='connectToCalendar',
            field=models.BooleanField(default=False),
        ),
    ]
