# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-03-24 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0011_sarvouser_connecttocalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarvouser',
            name='agreedDSGVO',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
    ]
