# Generated by Django 2.0 on 2020-04-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0013_auto_20200414_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowseEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, default='Empty', max_length=100)),
                ('title', models.CharField(blank=True, default='Empty', max_length=100)),
                ('image', models.CharField(blank=True, default='Empty', max_length=1000000)),
                ('description', models.CharField(blank=True, default='Empty', max_length=5000)),
                ('starChosen', models.BooleanField(default=True)),
                ('categoryTitle', models.CharField(blank=True, default='Empty', max_length=100)),
            ],
        ),
    ]
