# Generated by Django 2.0 on 2020-04-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0014_browseevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browseevent',
            name='description',
            field=models.CharField(blank=True, default='Empty', max_length=500000),
        ),
    ]
