# Generated by Django 2.0 on 2020-04-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0016_browseevent_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browseevent',
            name='description',
            field=models.CharField(blank=True, default='Empty', max_length=50000),
        ),
        migrations.AlterField(
            model_name='sarvoevent',
            name='description',
            field=models.CharField(blank=True, default='Empty', max_length=50000),
        ),
    ]
