# Generated by Django 2.0 on 2020-05-09 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0017_auto_20200416_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborativeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unnamed List', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CollaborativeListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='leer', max_length=100)),
                ('collabList', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='collablist', to='rest.CollaborativeList')),
            ],
        ),
        migrations.CreateModel(
            name='CollaborativeListItemDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, default='leer', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rest.SarvoUser')),
            ],
        ),
        migrations.AddField(
            model_name='collaborativelistitem',
            name='details',
            field=models.ManyToManyField(related_name='collablistitemdetail', to='rest.CollaborativeListItemDetail'),
        ),
    ]
