# Generated by Django 2.0 on 2020-05-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0018_auto_20200509_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarvoevent',
            name='collaborativeLists',
            field=models.ManyToManyField(related_name='collablists', to='rest.CollaborativeList'),
        ),
    ]
