# Generated by Django 2.0 on 2020-09-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0019_sarvoevent_collaborativelists'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateReceived', models.CharField(default='Empty', max_length=100)),
                ('content', models.CharField(default='Empty', max_length=5000)),
            ],
        ),
        migrations.RemoveField(
            model_name='collaborativelistitem',
            name='collabList',
        ),
        migrations.RemoveField(
            model_name='collaborativelistitem',
            name='details',
        ),
        migrations.RemoveField(
            model_name='collaborativelistitemdetail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sarvoevent',
            name='collaborativeLists',
        ),
        migrations.DeleteModel(
            name='CollaborativeList',
        ),
        migrations.DeleteModel(
            name='CollaborativeListItem',
        ),
        migrations.DeleteModel(
            name='CollaborativeListItemDetail',
        ),
    ]
