# Generated by Django 2.0 on 2020-09-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0020_auto_20200908_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplecontent',
            name='project',
            field=models.CharField(default='Empty', max_length=50),
        ),
    ]
