# Generated by Django 2.0 on 2021-12-16 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0021_simplecontent_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sarvouser',
            name='authenticationUser',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
