# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='event.proto',
  package='sarvo',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x65vent.proto\x12\x05sarvo\"&\n\nEventProto\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04name\x18\x02 \x02(\t\"3\n\x0e\x45ventListProto\x12!\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x11.sarvo.EventProto')
)




_EVENTPROTO = _descriptor.Descriptor(
  name='EventProto',
  full_name='sarvo.EventProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sarvo.EventProto.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='sarvo.EventProto.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=60,
)


_EVENTLISTPROTO = _descriptor.Descriptor(
  name='EventListProto',
  full_name='sarvo.EventListProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='events', full_name='sarvo.EventListProto.events', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=113,
)

_EVENTLISTPROTO.fields_by_name['events'].message_type = _EVENTPROTO
DESCRIPTOR.message_types_by_name['EventProto'] = _EVENTPROTO
DESCRIPTOR.message_types_by_name['EventListProto'] = _EVENTLISTPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EventProto = _reflection.GeneratedProtocolMessageType('EventProto', (_message.Message,), dict(
  DESCRIPTOR = _EVENTPROTO,
  __module__ = 'event_pb2'
  # @@protoc_insertion_point(class_scope:sarvo.EventProto)
  ))
_sym_db.RegisterMessage(EventProto)

EventListProto = _reflection.GeneratedProtocolMessageType('EventListProto', (_message.Message,), dict(
  DESCRIPTOR = _EVENTLISTPROTO,
  __module__ = 'event_pb2'
  # @@protoc_insertion_point(class_scope:sarvo.EventListProto)
  ))
_sym_db.RegisterMessage(EventListProto)


# @@protoc_insertion_point(module_scope)
