# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: group.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='group.proto',
  package='sarvo',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0bgroup.proto\x12\x05sarvo\"\x18\n\nGroupProto\x12\n\n\x02id\x18\x01 \x02(\x05')
)




_GROUPPROTO = _descriptor.Descriptor(
  name='GroupProto',
  full_name='sarvo.GroupProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sarvo.GroupProto.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=46,
)

DESCRIPTOR.message_types_by_name['GroupProto'] = _GROUPPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GroupProto = _reflection.GeneratedProtocolMessageType('GroupProto', (_message.Message,), dict(
  DESCRIPTOR = _GROUPPROTO,
  __module__ = 'group_pb2'
  # @@protoc_insertion_point(class_scope:sarvo.GroupProto)
  ))
_sym_db.RegisterMessage(GroupProto)


# @@protoc_insertion_point(module_scope)
